# Generated by Django 5.2 on 2025-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='firebase_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
